# Generated by Django 6.0.6 on 2026-06-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('estimated_hours', models.IntegerField()),
                ('github_template', models.URLField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('skills_required', models.ManyToManyField(to='assessments.skill')),
            ],
        ),
    ]
